#!/bin/bash
# tsinghua net usage
# ... for accurate data,
# ... ... use flag `--refresh`
# ... ... or set variable `TSINGHUA_NET_ACCURATE`

[[ -n $TSINGHUA_NET_TIMESTAMP ]] \
    || TSINGHUA_NET_TIMESTAMP=/tmp/tsinghua-net.timestamp

[[ -n $TSINGHUA_NET_TIMEOUT ]] \
    || TSINGHUA_NET_TIMEOUT=$(( 30 * 60 ))

[[ $1 == --refresh ]] && refresh=1

if timestamp=$(cat $TSINGHUA_NET_TIMESTAMP) \
    && [[ $(( $(date +%s) - timestamp )) -lt $TSINGHUA_NET_TIMEOUT ]];
then :
elif [[ -n $TSINGHUA_NET_ACCURATE ]]; then
    refresh=1
fi

if [[ -n $refresh ]]; then
    timeout 2 tsinghua-net-relogin
    sleep 1
fi

tsinghua-net status | grep '流量' | grep -v '￥' | sed 's/^.*：//g'
